name: Tests

on: ['push', 'pull_request']

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.4 ]

    name: Tests — PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add Flux Credentials Loaded From ENV
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: iconv, intl
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress --ansi
          npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: List installed dependencies
        run: composer show -D

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Build assets
        run: npm run build

      - name: Unit tests
        run: composer test:unit
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
          CASHIER_PRODUCT_MEMBERSHIP_AGEPAC: ${{ secrets.CASHIER_PRODUCT_MEMBERSHIP_AGEPAC }}
          CASHIER_PRODUCT_MEMBERSHIP_AGEPAC_ALUMNI: ${{ secrets.CASHIER_PRODUCT_MEMBERSHIP_AGEPAC_ALUMNI }}
